version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: fsc_production_DB
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kanta
      MYSQL_PASSWORD: kanta
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  prod:
    environment:
      RAILS_ENV: 'production'
      RACK_ENV: 'production'
    build: .
    volumes:
      - .:/FSC_app
      - public-data:/FSC_app/public
      - tmp-data:/FSC_app/tmp
      - log-data:/FSC_app/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bundle exec puma -C config/puma.rb
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/FSC_app/public
      - tmp-data:/FSC_app/tmp
    ports:
      - 80:80
    depends_on:
      - prod
volumes:
  mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
  db-data:
