version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - '3306:3306' # ホストからゲストへポートフォワード
    environment:
      MYSQL_DATABASE: fsc_development_DB
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kanta
      MYSQL_PASSWORD: kanta


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "yarn install && rm -f /FSC_app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/FSC_app # ソースコード変更したらDocker側も即反映されるように
